import «WideLocalMinorSquare»
import «MaximalMinorWeight»

/-!
# Fixed-pivot contraction for the maximal-minor square

The fixed `(n-1)`-minor is not in the maximal-minor ideal.  The generic
maximal-minor primality and power-primaryness theorems then cancel every
power of that pivot from membership in the square.
-/

noncomputable section

namespace WidePolynomial

open GeneralAsymmetricC1

def pivotSpecialization (k r : ℕ) : Mat (k + 1) (k + r) :=
  fun i a => if i.val < k ∧ i.val = a.val then 1 else 0

lemma pivotBlock_pivotSpecialization (k r : ℕ) :
    pivotBlock (pivotSpecialization k r) =
      (1 : Matrix (Fin k) (Fin k) ℝ) := by
  ext i j
  simp [pivotBlock, pivotSpecialization, pivotRow, pivotColumn,
    Matrix.one_apply, Fin.ext_iff]

lemma eval_pivotMinor_pivotSpecialization (k r : ℕ) :
    MvPolynomial.eval
        (fun ia => pivotSpecialization k r ia.1 ia.2)
        (pivotMinor k r) = 1 := by
  rw [eval_pivotMinor, pivotBlock_pivotSpecialization, Matrix.det_one]

lemma eval_maximalMinorPoly_pivotSpecialization
    (k r : ℕ) (S : MinorIndex (k + 1) (k + r)) :
    MvPolynomial.eval
        (fun ia => pivotSpecialization k r ia.1 ia.2)
        (maximalMinorPoly S) = 0 := by
  rw [eval_maximalMinorPoly]
  apply Matrix.det_eq_zero_of_row_eq_zero (Fin.last k)
  intro j
  simp [pivotSpecialization]

theorem pivotMinor_not_mem_maximalMinorIdeal (k r : ℕ) :
    pivotMinor k r ∉ maximalMinorIdeal (k + 1) (k + r) := by
  let ev : WidePoly (k + 1) (k + r) →+* ℝ :=
    MvPolynomial.eval (fun ia => pivotSpecialization k r ia.1 ia.2)
  have hle : maximalMinorIdeal (k + 1) (k + r) ≤ RingHom.ker ev := by
    rw [maximalMinorIdeal, Ideal.span_le]
    rintro q ⟨S, rfl⟩
    change ev (maximalMinorPoly S) = 0
    exact eval_maximalMinorPoly_pivotSpecialization k r S
  intro hpivot
  have hz : ev (pivotMinor k r) = 0 := hle hpivot
  rw [show ev (pivotMinor k r) = 1 from
    eval_pivotMinor_pivotSpecialization k r] at hz
  norm_num at hz

/-! ## Elementary boundary cases and power reduction -/

/-- The unique increasing self-embedding used to index the determinant in
the square case. -/
def squareMinorIndex (n : ℕ) : MinorIndex n n :=
  OrderEmbedding.id (Fin n)

/-- An increasing self-embedding of `Fin n` is the identity.  This is kept
local to the determinantal API because `MinorIndex n n` does not have a
`Subsingleton` instance in mathlib. -/
lemma square_minorIndex_eq (n : ℕ) (S : MinorIndex n n) :
    S = squareMinorIndex n := by
  let eo : Fin n ≃o Fin n := RelIso.ofSurjective S
    (Finite.injective_iff_surjective.mp S.injective)
  apply DFunLike.ext _ _
  intro i
  apply Fin.ext
  simpa [squareMinorIndex, eo] using Fin.coe_orderIso_apply eo i

lemma maximalMinorPoly_squareMinorIndex (n : ℕ) :
    maximalMinorPoly (squareMinorIndex n) =
      SquarePolynomial.genericDetPoly ℝ n := by
  rfl

/-- For a square generic matrix the maximal-minor ideal is the principal
ideal generated by the generic determinant. -/
lemma maximalMinorIdeal_square (n : ℕ) :
    maximalMinorIdeal n n =
      Ideal.span {SquarePolynomial.genericDetPoly ℝ n} := by
  rw [maximalMinorIdeal]
  congr 1
  ext f
  constructor
  · rintro ⟨S, rfl⟩
    rw [square_minorIndex_eq n S, maximalMinorPoly_squareMinorIndex]
    exact Set.mem_singleton _
  · intro hf
    rw [Set.mem_singleton_iff] at hf
    subst f
    exact ⟨squareMinorIndex n, maximalMinorPoly_squareMinorIndex n⟩

/-- Fixed-pivot cancellation for the square boundary case `r = 1`.  Here
the maximal-minor ideal is principal, so generic determinant irreducibility
and ordinary prime divisibility suffice; no straightening theorem is needed. -/
theorem mem_maximalMinorIdeal_sq_of_pivot_mul_mem_square
    (k : ℕ) (f : WidePoly (k + 1) (k + 1))
    (hf : pivotMinor k 1 * f ∈
      maximalMinorIdeal (k + 1) (k + 1) ^ 2) :
    f ∈ maximalMinorIdeal (k + 1) (k + 1) ^ 2 := by
  let d : WidePoly (k + 1) (k + 1) :=
    SquarePolynomial.genericDetPoly ℝ (k + 1)
  have hdprime : Prime d :=
    UniqueFactorizationMonoid.irreducible_iff_prime.mp
      (SquarePolynomial.genericDetPoly_irreducible (K := ℝ) (k + 1)
        (by omega))
  have hnotdvd : ¬d ∣ pivotMinor k 1 := by
    intro hdvd
    have hpivot : pivotMinor k 1 ∈
        maximalMinorIdeal (k + 1) (k + 1) := by
      rw [maximalMinorIdeal_square (k + 1), Ideal.mem_span_singleton]
      exact hdvd
    exact pivotMinor_not_mem_maximalMinorIdeal k 1 hpivot
  rw [maximalMinorIdeal_square (k + 1), Ideal.span_singleton_pow,
    Ideal.mem_span_singleton] at hf ⊢
  exact hdprime.pow_dvd_of_dvd_mul_left 2 hnotdvd hf

/-- A single fixed-pivot cancellation step cancels every positive power of
the same pivot.  This is the exact induction needed after denominator
extraction from the Schur localization. -/
lemma mem_of_pivot_pow_mul_mem_of_single_cancel
    {k r N : ℕ} {f : WidePoly (k + 1) (k + r)}
    (hcancel : ∀ g : WidePoly (k + 1) (k + r),
      pivotMinor k r * g ∈ maximalMinorIdeal (k + 1) (k + r) ^ 2 →
        g ∈ maximalMinorIdeal (k + 1) (k + r) ^ 2)
    (hf : pivotMinor k r ^ N * f ∈
      maximalMinorIdeal (k + 1) (k + r) ^ 2) :
    f ∈ maximalMinorIdeal (k + 1) (k + r) ^ 2 := by
  induction N generalizing f with
  | zero => simpa using hf
  | succ N ih =>
      apply ih
      apply hcancel
      simpa [pow_succ, mul_assoc, mul_comm, mul_left_comm] using hf

lemma mem_of_pivot_pow_mul_mem_of_primary
    {k r N : ℕ} {f : WidePoly (k + 1) (k + r)}
    (hprime : (maximalMinorIdeal (k + 1) (k + r)).IsPrime)
    (hprimary : (maximalMinorIdeal (k + 1) (k + r) ^ 2).IsPrimary)
    (hf : pivotMinor k r ^ N * f ∈
      maximalMinorIdeal (k + 1) (k + r) ^ 2) :
    f ∈ maximalMinorIdeal (k + 1) (k + r) ^ 2 := by
  cases N with
  | zero => simpa using hf
  | succ N =>
      have hf' : f * pivotMinor k r ^ (N + 1) ∈
          maximalMinorIdeal (k + 1) (k + r) ^ 2 := by
        rwa [mul_comm]
      rcases (Ideal.isPrimary_iff.mp hprimary).2 hf' with hf | hpivot
      · exact hf
      · have hradical :
            (maximalMinorIdeal (k + 1) (k + r) ^ 2).radical =
              maximalMinorIdeal (k + 1) (k + r) := by
          rw [Ideal.radical_pow (maximalMinorIdeal (k + 1) (k + r))
            (by norm_num : (2 : ℕ) ≠ 0), hprime.radical]
        rw [hradical] at hpivot
        have hpivot' :
            pivotMinor k r ∈ maximalMinorIdeal (k + 1) (k + r) :=
          (hprime.pow_mem_iff_mem (N + 1) (Nat.succ_pos N)).mp hpivot
        exact False.elim ((pivotMinor_not_mem_maximalMinorIdeal k r) hpivot')

/-! ## The generic determinantal theorem in the wide-polynomial API -/

/-- `WidePolynomial.maximalMinorIdeal` and the coefficient-polymorphic
generic maximal-minor ideal are definitionally the same over `ℝ`. -/
lemma maximalMinorIdeal_eq_maximalMinorIdealOver
    {n m : ℕ} (hnm : n ≤ m) :
    maximalMinorIdeal n m =
      GenericMaximalMinor.maximalMinorIdealOver ℝ n m hnm := by
  rfl

/-- The maximal-minor ideal of a generic `(k+1) × (k+r)` real matrix is
prime as soon as there is at least one nonpivot column. -/
theorem maximalMinorIdeal_isPrime {k r : ℕ} (hr : 0 < r) :
    (maximalMinorIdeal (k + 1) (k + r)).IsPrime := by
  rw [maximalMinorIdeal_eq_maximalMinorIdealOver (by omega : k + 1 ≤ k + r)]
  exact GenericMaximalMinor.maximalMinorIdealOver_isPrime
    (D := ℝ) (by omega : k + 1 ≤ k + r)

/-- The square of the maximal-minor ideal of a generic wide real matrix is
primary to the maximal-minor ideal. -/
theorem maximalMinorIdeal_sq_isPrimary {k r : ℕ} (hr : 0 < r) :
    (maximalMinorIdeal (k + 1) (k + r) ^ 2).IsPrimary := by
  rw [maximalMinorIdeal_eq_maximalMinorIdealOver (by omega : k + 1 ≤ k + r)]
  exact GenericMaximalMinor.maximalMinorIdealOver_sq_isPrimary
    (D := ℝ) (by omega : k + 1 ≤ k + r)

/-- Global fixed-pivot saturation: the artificial denominator introduced by
the Schur chart can be cancelled completely. -/
theorem mem_maximalMinorIdeal_sq_of_pivot_pow_mul_mem
    {k r N : ℕ} (hr : 0 < r) {f : WidePoly (k + 1) (k + r)}
    (hf : pivotMinor k r ^ N * f ∈
      maximalMinorIdeal (k + 1) (k + r) ^ 2) :
    f ∈ maximalMinorIdeal (k + 1) (k + r) ^ 2 := by
  exact mem_of_pivot_pow_mul_mem_of_primary
    (maximalMinorIdeal_isPrime hr) (maximalMinorIdeal_sq_isPrimary hr) hf

#print axioms pivotMinor_not_mem_maximalMinorIdeal
#print axioms mem_maximalMinorIdeal_sq_of_pivot_mul_mem_square
#print axioms mem_of_pivot_pow_mul_mem_of_single_cancel
#print axioms maximalMinorIdeal_isPrime
#print axioms maximalMinorIdeal_sq_isPrimary
#print axioms mem_maximalMinorIdeal_sq_of_pivot_pow_mul_mem

end WidePolynomial
